#!/usr/bin/env python3

import sys
from main import sync

def help():
    print("""
SpotiFlopy CLI

Commands:
  spotiflopy sync       Sync Spotify liked songs
  spotiflopy help       Show this help
""")

if len(sys.argv) < 2:
    help()
    sys.exit()

cmd = sys.argv[1]

if cmd == "sync":
    sync()
else:
    help()